### ISSUE TITLE
could you add support of Manjaro?

### ISSUE THREAD

**Issue by c0b** [thias/glim#17]
it stays in the distrowatch popularity top3 for a long time already, hope you can include here

1. http://distrowatch.com/dwres.php?resource=popularity
2. https://manjaro.org/

it's ArchLinux based, since you support Arch already, add Manjaro should be easy?

**Comment by thias** [comment]
Sure, I'll try to have a look at adding it (though I don't know when).
Feel free to try yourself, it's fairly straightforward, see for instance 3cc3f08f3762a81f7a2da1c7222564c90a1414a5 where @sradigan added an Arch-based distro.

**Comment by thias** [comment]
Done at last in fe9f36cf4a2f8e669b5a0db4b09fddbdbada12c1.
