### ISSUE TITLE
Suggestion: Adding functionality from Super Grub2 Disk

### ISSUE THREAD

**Issue by umasse** [thias/glim#25]
Hi,
This is just a suggestion: I have been using Super Grub2 Disk recently, and it has some great functionality to auto detect installed OSs, grub.cfg files, and other possible ways to boot your machine. It seems to all be just some clever scripts, but it could be extremely useful.

I have been able to add the ISO to my GLIM usb, and added this as inc-sgd.cfg
```
# Super Grub2 Disk
set isoname="super_grub2_disk_hybrid_2.02s9.iso"
set isofile="${isopath}/sgd/${isoname}"
menuentry "Super Grub2 Disk" --class arch {
  echo "Using ${isoname}..."
  loopback loop $isofile
  source (loop)/boot/grub/grub.cfg
}
```

but I suspect it would be a better idea to integrate the scripts in GLIM itself. Here is the Github code:
https://github.com/supergrub/supergrub/

**Comment by thias** [comment]
I actually like the source approach, to avoid having to duplicate complex boot choices into glim. The `configfile` might be better suited in some cases, as I have just found out with grml. I'll look into adding this cleanly to glim.

**Comment by thias** [comment]
Support added in 80fd2a7ee9b3ac7b6bf2a2d8501e5233d9c45879.
(note that this is the first ISO image that doesn't require a sub-directory inside "iso", as I plan to change all of them to be like this soon)
