### ISSUE TITLE
Grub config handler or distro image downloader

### ISSUE THREAD

**Issue by DanySpin97** [thias/glim#27]
Update ISO for each release is required to keep glim updated; so if I download the latest version of Arch Linux, I will have to manually update all other ISO.
It is possibile to update manually the single config file, but it would get worse in the long-term.
I don't think this is a suitable behavior.

I thought of two ways to improve this behavior:
- provide a script to download and update all supported ISO
- provide a base grub configuration file for each distro and a patch file for each distro release; a script will checkout provided distro in the drive and apply all the needed patches.

I can work on this, but i want to discuss the implementation first.

**Comment by thias** [comment]
My recent discovery of the regexp grub module seems to take care of this: Menu entries will be created dynamically at runtime based on the files that are present. Version info is extracted from file names. Most updates should "just work" after adding or replacing newer ISO image files. See the latest CentOS, Ubuntu or Linux Mint files for some examples.
