### ISSUE TITLE
Write a GRUB module to detect the ISOs

### ISSUE THREAD

**Issue by probonopd** [thias/glim#35]
Would it be possible to write a GRUB module to do detect the ISOs rather than hardcoding certain versions? I might be interested in this for the [SystemImageKit](https://github.com/probonopd/SystemImageKit) project, too.

**Comment by vflyson** [comment]
Please see my comment here: https://github.com/thias/glim/issues/34#issuecomment-450528342

**Comment by thias** [comment]
I have started reworking some of the files, using the regexp grub2 module. It allows to expand a shell-like file glob, to get a list of available files, and also to extract version, arch, variant, etc. from the file names to construct "dynamic" menu entries. See CentOS, Ubuntu or Linux Mint files to see how it goes, as I'm guessing it's what you wanted (and what I had wanted for a long time too!).
