### ISSUE TITLE
Iconsistancies with sysrescd (and possibly elsewhere)?

### ISSUE THREAD

**Issue by MrLightningBlaze** [thias/glim#60]
`glim/grub2/grub.cfg` refers to sysrescd as `systemrescuecd-*.iso` to check
but, for some reason, `glib/grub2/inc-sysrescd.cfg` refers to it as `systemrescuecd-x86-*.iso`
This can lead to issues where an iso like `systemrescuecd-amd64-*.iso` can make an entry appear, but not actually be openable

**Comment by thias** [comment]
This seems related to the project's switch from Gentoo to Arch. The inc file needs to be completely redone, because the single x86 iso no longer seems to exist and has been replaced by two files, an amd64 and an i686 one. PR welcome :-)

**Comment by thias** [comment]
I have finally taken the time to review and test this. Upstream SystemRescueCd has changed a lot, so I've cleaned it all up in ac730a7bd30e4c51963057f86b29527d79bdbcb0.
