### ISSUE TITLE
ERROR: grub2-install or grub-install commands not found.

### ISSUE THREAD

**Issue by antosamalona** [thias/glim#65]
Hello there! I got this message when I ran it on my debian machine.

**Comment by thias** [comment]
You need to find out what package provides either of those on debian and install it. I think something like `apt-cache search grub-install` would be a good start. There is unfortunately no unique package name for this across all GNU/Linux distributions (or even command for that matter, as the error indicates).

**Comment by Michae1Weiss** [comment]
I had the same problem on **Debian 11**.

The `grub-install` command was missing, but other GRUB-related commands like `grub-editenv` were available.
### Solution:
To fix the issue, I added the missing directories (`/usr/sbin`, `/sbin`, etc.) to my `$PATH` so the system could locate the `grub-install` command.

Run this command in your terminal to temporarily update your `$PATH`:
```bash
export PATH=$PATH:/usr/local/sbin:/usr/sbin:/sbin
```

After doing this, I could confirm that `grub-install` was found by running:
```bash
which grub-install
```
Output:
```
/usr/sbin/grub-install
```
