### ISSUE TITLE
Failure grub-install: device.map missing - but this is unavailable in Arch Linux

### ISSUE THREAD

**Issue by cmonty14** [thias/glim#66]
Hi,
the script is executing this command to install Grub2:
`sudo ${GRUB2_INSTALL} ${GRUB_TARGET} --boot-directory=${USBMNT}/boot ${USBDEV}`
or
`sudo grub-install --target=x86_64-efi --efi-directory=/mnt/tmp --removable --boot-directory=/mnt/tmp/boot /dev/sdd1`

However, there's no _device.map_ in /boot/grub/ on Arch Linux.
And there's no `grub-mkdevicemap` to create it.

Please advise how to fix this issue?

THX

**Comment by thias** [comment]
I don't use Arch, and have never run into this on Fedora. I don't see any device.map file on Fedora either, nor in the files installed for GLIM. My guess is that this is a generic or misleading message, and the actual problem could have been elsewhere. Please reopen with further details if this is still relevant.
