### ISSUE TITLE
Can't get past "Welcome to GRUB" screen

### ISSUE THREAD

**Issue by vflyson** [thias/glim#8]
Tested on two different physical machines, with two different USB sticks.
The installation process completes with no errors, but I never get to the actual boot menu.

Most likely there's something wrong with the configuration.
The host system where I run grub2-install is OpenSUSE 42.x.

Tried both FAT32 and ext4 partition type (MBR, of course).

I've been ready to start my own project with a similar concept, but was happy to find your work
Thank you for sharing it. I would like to help you fix and improve it.

**Comment by dufresnep** [comment]
I thought/think that menuentry cannot be put inside an if.

**Comment by thias** [comment]
Given how old this report is, I'll go ahead and close it (sorry!). If it's still relevant, please do reopen it.
