### ISSUE TITLE
Typo in file glim/grub2/inc-linuxmint.cfg 

### ISSUE THREAD

**Issue by zirneklitis** [thias/glim#89]
Hi!

There is a typo in the glim/grub2/inc-linuxmint.cfg file. The name of Debian based «Linux Mint» live cd  images begins with “lmde”.

Best regards
[inc-linuxmint.diff.txt](https://github.com/thias/glim/files/9382283/inc-linuxmint.diff.txt)
.

**Comment by thias** [comment]
Thanks a lot for the report!
